### ISSUE TITLE
Node example pubsub 'subscription-change' error

### ISSUE THREAD

**Issue by omilli** [orbitdb/orbitdb-examples#1]
Running the node example gives the following error.

```bash
examples/nodejs/node_modules/@orbitdb/core/src/sync.js:274
      pubsub.addEventListener('subscription-change', handlePeerSubscribed)
             ^

TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at startSync (examples/nodejs/node_modules/@orbitdb/core/src/sync.js:274:14)
    at async Sync (examples/nodejs/node_modules/@orbitdb/core/src/sync.js:284:5)
    at async Database (examples/nodejs/node_modules/@orbitdb/core/src/database.js:188:16)
    at async examples/nodejs/node_modules/@orbitdb/core/src/databases/keyvalue.js:19:20
    at async Object.open (examples/nodejs/node_modules/@orbitdb/core/src/orbitdb.js:156:16)
    at async examples/nodejs/node_modules/@orbitdb/core/src/access-controllers/orbitdb.js:40:14
    at async Object.open (examples/nodejs/node_modules/@orbitdb/core/src/orbitdb.js:136:26)
    at async examples/nodejs/index.js:73:8

Node.js v20.11.0
```

**Comment by haydenyoung** [comment]
Thanks for reporting the issue. It should now be resolved. Please git pull and run again.
